/**
 * Generates src/admin/manifest.gen.ts — a static manifest of all admin
 * route modules and island files.
 *
 * Why this exists: Fresh's `app.fsRoutes()` discovers route files by
 * scanning a local directory at build time. When Dune runs from JSR,
 * `import.meta.url` is an https:// URL and there is no local directory
 * to scan, so fsRoutes() silently registers nothing and every /admin
 * request 404s. The manifest replaces directory scanning with static
 * imports, which work identically from JSR and from a local checkout.
 *
 * Run after adding, removing, or renaming files under src/admin/routes/
 * or src/admin/islands/:
 *
 *   deno task gen:admin-manifest
 *
 * The test in tests/admin_manifest_test.ts fails when the manifest is
 * out of date.
 */

import { walk } from "@std/fs";
import { fromFileUrl, join, relative } from "@std/path";

const adminDir = fromFileUrl(new URL("../src/admin", import.meta.url));
const routesDir = join(adminDir, "routes");
const islandsDir = join(adminDir, "islands");

/** Convert a route file path (relative to routes/) to a Fresh URL pattern. */
function pathToPattern(relPath: string): string {
  const noExt = relPath.replace(/\.(ts|tsx)$/, "");
  const parts = noExt.split("/");
  if (parts[parts.length - 1] === "index") parts.pop();

  let route = "";
  for (const part of parts) {
    if (part.startsWith("[...") && part.endsWith("]")) {
      route += `/:${part.slice(4, -1)}*`;
    } else if (part.startsWith("[") && part.endsWith("]")) {
      route += `/:${part.slice(1, -1)}`;
    } else {
      route += `/${part}`;
    }
  }
  return route === "" ? "/" : route;
}

/**
 * Sort patterns so more specific routes are registered first:
 * static segments before :params before :wildcards*, segment by segment.
 */
function comparePatterns(a: string, b: string): number {
  const sa = a.split("/").filter(Boolean);
  const sb = b.split("/").filter(Boolean);
  const len = Math.max(sa.length, sb.length);
  for (let i = 0; i < len; i++) {
    const x = sa[i];
    const y = sb[i];
    if (x === undefined) return -1;
    if (y === undefined) return 1;
    if (x === y) continue;
    const rank = (s: string) => s.endsWith("*") ? 2 : s.startsWith(":") ? 1 : 0;
    const rx = rank(x);
    const ry = rank(y);
    if (rx !== ry) return rx - ry;
    return x < y ? -1 : 1;
  }
  return 0;
}

export async function generateManifest(): Promise<string> {
  const routeFiles: string[] = [];
  for await (const entry of walk(routesDir, { includeDirs: false, exts: [".ts", ".tsx"] })) {
    const rel = relative(routesDir, entry.path);
    // Skip _middleware.ts, _layout.tsx, and helpers like api/_utils.ts.
    if (rel.split("/").some((seg) => seg.startsWith("_"))) continue;
    routeFiles.push(rel);
  }

  const routes = routeFiles
    .map((rel) => ({ rel, pattern: pathToPattern(rel) }))
    .sort((a, b) => comparePatterns(a.pattern, b.pattern));

  const islands: string[] = [];
  for await (const entry of walk(islandsDir, { includeDirs: false, exts: [".tsx"] })) {
    const rel = relative(islandsDir, entry.path);
    if (rel.startsWith("_")) continue;
    islands.push(rel);
  }
  islands.sort();

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-admin-manifest.ts — do not edit.",
    "// Regenerate with: deno task gen:admin-manifest",
    "",
    'import * as middlewareMod from "./routes/_middleware.ts";',
    'import * as layoutMod from "./routes/_layout.tsx";',
  ];

  routes.forEach(({ rel }, i) => {
    lines.push(`import * as r${i} from "./routes/${rel}";`);
  });

  lines.push(
    "",
    "/** Shape of an fs-convention route module (subset Fresh cares about). */",
    "export interface AdminRouteModule {",
    "  default?: unknown;",
    "  handler?: unknown;",
    "  handlers?: unknown;",
    "  config?: unknown;",
    "}",
    "",
    "export interface AdminRouteEntry {",
    "  /** URL pattern relative to the admin prefix, e.g. \"/pages/:path\" */",
    "  pattern: string;",
    "  mod: AdminRouteModule;",
    "}",
    "",
    "export const adminMiddleware = middlewareMod;",
    "export const adminLayout = layoutMod;",
    "",
    "export const adminRoutes: AdminRouteEntry[] = [",
  );
  routes.forEach(({ pattern }, i) => {
    lines.push(`  { pattern: ${JSON.stringify(pattern)}, mod: r${i} },`);
  });
  lines.push(
    "];",
    "",
    "/** Island files under src/admin/islands/, for Builder.registerIsland(). */",
    "export const adminIslands: string[] = [",
  );
  for (const island of islands) {
    lines.push(`  ${JSON.stringify(island)},`);
  }
  lines.push("];", "");

  return lines.join("\n");
}

if (import.meta.main) {
  const content = await generateManifest();
  const outPath = join(adminDir, "manifest.gen.ts");
  await Deno.writeTextFile(outPath, content);
  console.log(`Wrote ${outPath}`);
}
