// AUTO-GENERATED by scripts/generate-admin-manifest.ts — do not edit.
// Regenerate with: deno task gen:admin-manifest

import * as middlewareMod from "./routes/_middleware.ts";
import * as layoutMod from "./routes/_layout.tsx";
import * as r0 from "./routes/index.tsx";
import * as r1 from "./routes/api/audit.ts";
import * as r2 from "./routes/api/comments/mentions/index.ts";
import * as r3 from "./routes/api/comments/mentions/read.ts";
import * as r4 from "./routes/api/config/index.ts";
import * as r5 from "./routes/api/config/theme.ts";
import * as r6 from "./routes/api/config/theme-config.ts";
import * as r7 from "./routes/api/config/themes.ts";
import * as r8 from "./routes/api/content/[...rest].ts";
import * as r9 from "./routes/api/content-editor/ws.ts";
import * as r10 from "./routes/api/dashboard.ts";
import * as r11 from "./routes/api/dev/apply.ts";
import * as r12 from "./routes/api/editor/parse.ts";
import * as r13 from "./routes/api/editor/serialize.ts";
import * as r14 from "./routes/api/email-preview.ts";
import * as r15 from "./routes/api/email-preview/[id].ts";
import * as r16 from "./routes/api/flex/[type]/index.ts";
import * as r17 from "./routes/api/flex/[type]/[id]/index.ts";
import * as r18 from "./routes/api/history/[...rest].ts";
import * as r19 from "./routes/api/i18n/memory/index.ts";
import * as r20 from "./routes/api/i18n/memory/rebuild.ts";
import * as r21 from "./routes/api/i18n/mt-status.ts";
import * as r22 from "./routes/api/i18n/translate-page.ts";
import * as r23 from "./routes/api/i18n/translate-segment.ts";
import * as r24 from "./routes/api/inline-edit/presence.ts";
import * as r25 from "./routes/api/introspect.ts";
import * as r26 from "./routes/api/jobs.ts";
import * as r27 from "./routes/api/jobs/[name]/run.ts";
import * as r28 from "./routes/api/media/index.ts";
import * as r29 from "./routes/api/media/meta.ts";
import * as r30 from "./routes/api/media/upload.ts";
import * as r31 from "./routes/api/metrics.ts";
import * as r32 from "./routes/api/page-source.ts";
import * as r33 from "./routes/api/pages/index.ts";
import * as r34 from "./routes/api/pages/reorder.ts";
import * as r35 from "./routes/api/pages/translate.ts";
import * as r36 from "./routes/api/pages/[path]/index.ts";
import * as r37 from "./routes/api/pages/[path]/comments/index.ts";
import * as r38 from "./routes/api/pages/[path]/comments/[id]/index.ts";
import * as r39 from "./routes/api/pages/[path]/comments/[id]/resolve.ts";
import * as r40 from "./routes/api/plugins/index.ts";
import * as r41 from "./routes/api/plugins/install.ts";
import * as r42 from "./routes/api/plugins/[name]/config.ts";
import * as r43 from "./routes/api/preview.ts";
import * as r44 from "./routes/api/registry/plugins.ts";
import * as r45 from "./routes/api/registry/themes.ts";
import * as r46 from "./routes/api/render-markdown.ts";
import * as r47 from "./routes/api/search/analytics.ts";
import * as r48 from "./routes/api/sections.ts";
import * as r49 from "./routes/api/staging/[path]/index.ts";
import * as r50 from "./routes/api/staging/[path]/publish.ts";
import * as r51 from "./routes/api/theme-preview.ts";
import * as r52 from "./routes/api/themes/install.ts";
import * as r53 from "./routes/api/users/index.ts";
import * as r54 from "./routes/api/users/[id]/index.ts";
import * as r55 from "./routes/api/users/[id]/password.ts";
import * as r56 from "./routes/api/webhooks/deliveries.ts";
import * as r57 from "./routes/api/workflow/schedule/index.ts";
import * as r58 from "./routes/api/workflow/schedule/[id].ts";
import * as r59 from "./routes/api/workflow/scheduled/[path].ts";
import * as r60 from "./routes/api/workflow/stages.ts";
import * as r61 from "./routes/api/workflow/status/[path].ts";
import * as r62 from "./routes/api/workflow/transition.ts";
import * as r63 from "./routes/audit/index.tsx";
import * as r64 from "./routes/collab/edit-ws.ts";
import * as r65 from "./routes/collab/ws.ts";
import * as r66 from "./routes/config/index.tsx";
import * as r67 from "./routes/email-preview/index.tsx";
import * as r68 from "./routes/flex/index.tsx";
import * as r69 from "./routes/flex/[type]/index.tsx";
import * as r70 from "./routes/flex/[type]/[id].tsx";
import * as r71 from "./routes/i18n/index.tsx";
import * as r72 from "./routes/i18n/memory.tsx";
import * as r73 from "./routes/jobs/index.tsx";
import * as r74 from "./routes/login.tsx";
import * as r75 from "./routes/login/logout.ts";
import * as r76 from "./routes/marketplace/index.tsx";
import * as r77 from "./routes/media/index.tsx";
import * as r78 from "./routes/metrics/index.tsx";
import * as r79 from "./routes/pages/index.tsx";
import * as r80 from "./routes/pages/builder.tsx";
import * as r81 from "./routes/pages/edit.tsx";
import * as r82 from "./routes/pages/history.tsx";
import * as r83 from "./routes/plugins/index.tsx";
import * as r84 from "./routes/submissions/index.tsx";
import * as r85 from "./routes/submissions/[form]/index.tsx";
import * as r86 from "./routes/submissions/[form]/[id]/index.tsx";
import * as r87 from "./routes/submissions/[form]/[id]/delete.ts";
import * as r88 from "./routes/submissions/[form]/[id]/files/[filename].ts";
import * as r89 from "./routes/submissions/[form]/[id]/status.ts";
import * as r90 from "./routes/themes/index.tsx";
import * as r91 from "./routes/users/index.tsx";

/** Shape of an fs-convention route module (subset Fresh cares about). */
export interface AdminRouteModule {
  default?: unknown;
  handler?: unknown;
  handlers?: unknown;
  config?: unknown;
}

export interface AdminRouteEntry {
  /** URL pattern relative to the admin prefix, e.g. "/pages/:path" */
  pattern: string;
  mod: AdminRouteModule;
}

export const adminMiddleware = middlewareMod;
export const adminLayout = layoutMod;

export const adminRoutes: AdminRouteEntry[] = [
  { pattern: "/", mod: r0 },
  { pattern: "/api/audit", mod: r1 },
  { pattern: "/api/comments/mentions", mod: r2 },
  { pattern: "/api/comments/mentions/read", mod: r3 },
  { pattern: "/api/config", mod: r4 },
  { pattern: "/api/config/theme", mod: r5 },
  { pattern: "/api/config/theme-config", mod: r6 },
  { pattern: "/api/config/themes", mod: r7 },
  { pattern: "/api/content/:rest*", mod: r8 },
  { pattern: "/api/content-editor/ws", mod: r9 },
  { pattern: "/api/dashboard", mod: r10 },
  { pattern: "/api/dev/apply", mod: r11 },
  { pattern: "/api/editor/parse", mod: r12 },
  { pattern: "/api/editor/serialize", mod: r13 },
  { pattern: "/api/email-preview", mod: r14 },
  { pattern: "/api/email-preview/:id", mod: r15 },
  { pattern: "/api/flex/:type", mod: r16 },
  { pattern: "/api/flex/:type/:id", mod: r17 },
  { pattern: "/api/history/:rest*", mod: r18 },
  { pattern: "/api/i18n/memory", mod: r19 },
  { pattern: "/api/i18n/memory/rebuild", mod: r20 },
  { pattern: "/api/i18n/mt-status", mod: r21 },
  { pattern: "/api/i18n/translate-page", mod: r22 },
  { pattern: "/api/i18n/translate-segment", mod: r23 },
  { pattern: "/api/inline-edit/presence", mod: r24 },
  { pattern: "/api/introspect", mod: r25 },
  { pattern: "/api/jobs", mod: r26 },
  { pattern: "/api/jobs/:name/run", mod: r27 },
  { pattern: "/api/media", mod: r28 },
  { pattern: "/api/media/meta", mod: r29 },
  { pattern: "/api/media/upload", mod: r30 },
  { pattern: "/api/metrics", mod: r31 },
  { pattern: "/api/page-source", mod: r32 },
  { pattern: "/api/pages", mod: r33 },
  { pattern: "/api/pages/reorder", mod: r34 },
  { pattern: "/api/pages/translate", mod: r35 },
  { pattern: "/api/pages/:path", mod: r36 },
  { pattern: "/api/pages/:path/comments", mod: r37 },
  { pattern: "/api/pages/:path/comments/:id", mod: r38 },
  { pattern: "/api/pages/:path/comments/:id/resolve", mod: r39 },
  { pattern: "/api/plugins", mod: r40 },
  { pattern: "/api/plugins/install", mod: r41 },
  { pattern: "/api/plugins/:name/config", mod: r42 },
  { pattern: "/api/preview", mod: r43 },
  { pattern: "/api/registry/plugins", mod: r44 },
  { pattern: "/api/registry/themes", mod: r45 },
  { pattern: "/api/render-markdown", mod: r46 },
  { pattern: "/api/search/analytics", mod: r47 },
  { pattern: "/api/sections", mod: r48 },
  { pattern: "/api/staging/:path", mod: r49 },
  { pattern: "/api/staging/:path/publish", mod: r50 },
  { pattern: "/api/theme-preview", mod: r51 },
  { pattern: "/api/themes/install", mod: r52 },
  { pattern: "/api/users", mod: r53 },
  { pattern: "/api/users/:id", mod: r54 },
  { pattern: "/api/users/:id/password", mod: r55 },
  { pattern: "/api/webhooks/deliveries", mod: r56 },
  { pattern: "/api/workflow/schedule", mod: r57 },
  { pattern: "/api/workflow/schedule/:id", mod: r58 },
  { pattern: "/api/workflow/scheduled/:path", mod: r59 },
  { pattern: "/api/workflow/stages", mod: r60 },
  { pattern: "/api/workflow/status/:path", mod: r61 },
  { pattern: "/api/workflow/transition", mod: r62 },
  { pattern: "/audit", mod: r63 },
  { pattern: "/collab/edit-ws", mod: r64 },
  { pattern: "/collab/ws", mod: r65 },
  { pattern: "/config", mod: r66 },
  { pattern: "/email-preview", mod: r67 },
  { pattern: "/flex", mod: r68 },
  { pattern: "/flex/:type", mod: r69 },
  { pattern: "/flex/:type/:id", mod: r70 },
  { pattern: "/i18n", mod: r71 },
  { pattern: "/i18n/memory", mod: r72 },
  { pattern: "/jobs", mod: r73 },
  { pattern: "/login", mod: r74 },
  { pattern: "/login/logout", mod: r75 },
  { pattern: "/marketplace", mod: r76 },
  { pattern: "/media", mod: r77 },
  { pattern: "/metrics", mod: r78 },
  { pattern: "/pages", mod: r79 },
  { pattern: "/pages/builder", mod: r80 },
  { pattern: "/pages/edit", mod: r81 },
  { pattern: "/pages/history", mod: r82 },
  { pattern: "/plugins", mod: r83 },
  { pattern: "/submissions", mod: r84 },
  { pattern: "/submissions/:form", mod: r85 },
  { pattern: "/submissions/:form/:id", mod: r86 },
  { pattern: "/submissions/:form/:id/delete", mod: r87 },
  { pattern: "/submissions/:form/:id/files/:filename", mod: r88 },
  { pattern: "/submissions/:form/:id/status", mod: r89 },
  { pattern: "/themes", mod: r90 },
  { pattern: "/users", mod: r91 },
];

/** Island files under src/admin/islands/, for Builder.registerIsland(). */
export const adminIslands: string[] = [
  "ConfigEditor.tsx",
  "FlexEditor.tsx",
  "Marketplace.tsx",
  "MediaLibrary.tsx",
  "MetricsDashboard.tsx",
  "PageBuilder.tsx",
  "PageEditor.tsx",
  "PageTree.tsx",
  "RevisionHistory.tsx",
  "TranslationMemory.tsx",
  "UserManager.tsx",
  "WorkflowPanel.tsx",
];
